import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const projectRoot = process.cwd();
const outputPath = path.resolve(projectRoot, "src/shared/sandbox-assets.generated.ts");
const assetPaths = [
  "Attachments/le-agreable.jpg",
  "Attachments/12th-street-rag.mp3",
  "Attachments/market-street-1906.mp4",
  "Attachments/beyond-earth-excerpt.pdf",
] as const;
const maximumAssetBytes = 1_000_000;
const maximumCombinedBytes = 3_000_000;

const entries: string[] = [];
let combinedBytes = 0;
for (const assetPath of assetPaths) {
  const sourcePath = path.resolve(projectRoot, "sandbox-vault", assetPath);
  const expectedRoot = path.resolve(projectRoot, "sandbox-vault");
  if (!sourcePath.startsWith(`${expectedRoot}${path.sep}`)) {
    throw new Error(`Sandbox asset path escapes its vault: ${assetPath}`);
  }
  const bytes = await readFile(sourcePath);
  if (bytes.length >= maximumAssetBytes) {
    throw new Error(`${assetPath} exceeds the ${maximumAssetBytes}-byte sandbox asset limit.`);
  }
  combinedBytes += bytes.length;
  const base64 = bytes.toString("base64");
  entries.push(`  ${JSON.stringify(assetPath)}: ${JSON.stringify(base64)},`);
}
if (combinedBytes >= maximumCombinedBytes) {
  throw new Error(`Sandbox assets exceed the ${maximumCombinedBytes}-byte combined limit.`);
}

const output = `// Generated by \`bun run sandbox:embed-assets\`. Do not edit directly.
export const SANDBOX_ASSET_BASE64 = {
${entries.join("\n")}
} as const;
`;

await writeFile(outputPath, output.replace(/\r?\n/g, "\r\n"), "utf8");
console.log(
  `Embedded ${assetPaths.length} sandbox assets in src/shared/sandbox-assets.generated.ts`,
);
